### ISSUE TITLE
Develop data model

### ISSUE THREAD

**Issue by grahamcrowell** [grahamcrowell/PortfolioBackTester#1]
tables, relationships
dims, facts

Dim.Stock
Fact.StockPrice

**Comment by grahamcrowell** [comment]
Java library for downloading stock data: [`com.yahoofinance-api`](http://financequotes-api.com/) has method: `getHistory(start, interval)`

it returns a collection of instances:

`INTC@2017-04-28: 35.880001-36.490002, 36.099998->36.150002 (36.150002)`

**Comment by grahamcrowell** [comment]
data can only be inserted when inserted at same time a schema creation...

need to learn **DBIO**

[Slick Database IO Actions](http://slick.lightbend.com/doc/3.1.0/dbio.html)

**Comment by dustinl8** [comment]
WIHandle connections - looking into streaming data. Not sure if the answer
